### ISSUE TITLE
Nome do arquivo em `config.properties`

### ISSUE THREAD

**Issue by nerun** [FastDevelopmentBR/rising-world-ptbr-translation#1]
Obrigado pela tradução amigo! Eu falo inglês fluentemente, mas é agradável poder ler em português do Brasil!

Só notei um problema pra instalar: o arquivo `config.properties` ainda não é capaz de detectar línguas regionais como `pt-br` (versão 0.6.7.2), mas `pt` funciona. Então eu tive que mudar o nome do arquivo de tradução de `pt-br.json` para `pt.json` e coloquei `pt` em `config.properties`. Aí funcionou.

Tem alguns errinhos de tradução, como "Creative" traduzido para "Creativo" quando o correto é "Criativo", com "i". Vou ver se consigo colaborar um pouco.

Obrigado!

**Comment by pablopereira27** [comment]
Na verdade atualmente o rising world permite sim inclusão de arquivo utilizando o codigo ISO da versão regional de um idioma, no nosso caso pt-br, como é mencionado no changelog da versão 0.6.7.

[Update 0.6.7: Posters, Signs and more Content](https://forum.rising-world.net/thread/12723-update-0-6-7-posters-signs-and-more-content/?postID=94793#post94793)
`[Change] The game now also detects regional languages (if you want to create custom localizations)` 

Basta incluir `Game_Language=pt-br` no arquivo `config.properties`

**Comment by pablopereira27** [comment]
Alguém para ajudar na tradução e revisão será muito bem vindo caso você tenha interesse em auxiliar mais ativamente.
